// Ready-made adverts for the newer services. Ad Studio → "Ready-made
// ads" loads one into the editor (download pictures, copy the caption,
// or put it in the app with one tap).
export const READY_ADS = [
  {
    key: 'pay-me-link',
    name: 'Pay me link',
    headline: 'Get paid with one link',
    highlight: 'one link',
    subtext: 'Create a Pay-me link, share it on WhatsApp — friends pay straight into your wallet',
    cta: 'Create my link',
    badges: ['Free', 'Instant', 'Any bank app'],
    emoji: '🔗',
    theme: 'purple',
    link: '/requests',
    inApp: 'Ask for money with a link — they pay, your wallet gets it instantly.',
    caption: 'Stop sending account numbers up and down 😅\n\nWith ZAPPI PAY, create a Pay-me link, share it on WhatsApp, and get paid straight into your wallet. Free and instant ⚡\n\n👉 www.zappipay.com.ng\n#ZappiPay #PayMeLink #GetPaid #Naija',
  },
  {
    key: 'split-bill',
    name: 'Split a bill',
    headline: 'Split the bill, no wahala',
    highlight: 'no wahala',
    subtext: 'Dinner, rent, fuel — ZAPPI PAY splits it and tracks who has paid',
    cta: 'Split a bill',
    badges: ['Track who paid', 'Reminders'],
    emoji: '🧾',
    theme: 'blue',
    link: '/requests',
    inApp: 'Split dinner, rent or fuel — see who has paid and who hasn’t.',
    caption: '"I go send am later" — we know that one 😂\n\nSplit any bill on ZAPPI PAY: everyone gets a link, pays their share, and you see who has paid. No more chasing people 🙌\n\n👉 www.zappipay.com.ng\n#ZappiPay #SplitTheBill #Naija',
  },
  {
    key: 'group-gift',
    name: 'Group gift',
    headline: 'Chip in for a group gift',
    highlight: 'group gift',
    subtext: 'Birthday, wedding, send-forth — collect contributions in one place',
    cta: 'Start a collection',
    badges: ['Birthdays', 'Weddings', 'Send-forth'],
    emoji: '🎁',
    theme: 'gold',
    link: '/requests',
    inApp: 'Birthday or wedding coming? Collect everyone’s contribution with one link.',
    caption: 'Birthday, wedding or send-forth loading? 🎉\n\nStart a group gift on ZAPPI PAY, share one link, and watch the contributions come in. Everyone can see the total 💛\n\n👉 www.zappipay.com.ng\n#ZappiPay #GroupGift #Owambe',
  },
  {
    key: 'car-insurance',
    name: 'Car insurance',
    headline: 'Car papers? Insurance in minutes',
    highlight: 'in minutes',
    subtext: 'Third-party motor insurance by Universal Insurance — certificate sent to your email',
    cta: 'Insure my car',
    badges: ['Cars', 'Buses', 'Keke & bikes'],
    emoji: '🚗',
    theme: 'green',
    link: '/insurance',
    inApp: 'Third-party motor insurance in minutes — certificate straight to your email.',
    caption: 'No more running around for car papers 🚗💨\n\nBuy third-party motor insurance on ZAPPI PAY in minutes — for cars, buses, keke and bikes. Your certificate comes straight to your email ✅\n\n👉 www.zappipay.com.ng\n#ZappiPay #CarInsurance #ThirdPartyInsurance',
  },
  {
    key: 'exam-pins',
    name: 'Bulk WAEC PINs',
    headline: 'WAEC PINs in bulk',
    highlight: 'in bulk',
    subtext: 'Buy up to 50 result checker PINs at once — print them on A4 or POS paper',
    cta: 'Buy exam PINs',
    badges: ['Schools', 'Cyber cafés', 'Agents'],
    emoji: '🎓',
    theme: 'dark',
    link: '/exam-pins',
    inApp: 'Schools & cyber cafés: buy up to 50 WAEC PINs at once and print them.',
    caption: 'Schools, cyber cafés and agents 📢\n\nBuy up to 50 WAEC result checker PINs at once on ZAPPI PAY, then print them neatly on A4 or your POS printer 🖨️ Agent prices apply.\n\n👉 www.zappipay.com.ng\n#ZappiPay #WAEC #ResultChecker #Schools',
  },
  {
    key: 'jamb-pin',
    name: 'JAMB PIN',
    headline: 'JAMB PIN without stress',
    highlight: 'without stress',
    subtext: 'Enter your Profile ID, we check your name, you get your PIN instantly',
    cta: 'Buy JAMB PIN',
    badges: ['UTME', 'With or without mock'],
    emoji: '📚',
    theme: 'red',
    link: '/buy/education',
    inApp: 'Buy your JAMB UTME PIN in seconds — your Profile ID is checked first.',
    caption: 'JAMB registration loading? 📚\n\nBuy your UTME PIN on ZAPPI PAY: enter your Profile ID, we confirm your name, and your PIN comes instantly. No queue, no stress ✅\n\n👉 www.zappipay.com.ng\n#ZappiPay #JAMB #UTME',
  },
];
