// Ready-made adverts for the newer services. Ad Studio → "Ready-made
// ads" loads one into the editor (download pictures, copy the caption,
// or put it in the app with one tap).
const ad = (key, name, emoji, theme, link, headline, highlight, subtext, cta, badges, inApp, caption, group = 'core') => ({ key, name, emoji, theme, link, headline, highlight, subtext, cta, badges, inApp, caption, group });
const SITE = '👉 www.zappipay.com.ng';

// Every service, so there's always a ready ad to post.
export const CORE_ADS = [
  ad('airtime', 'Airtime', '📱', 'purple', '/buy/airtime', 'Airtime in seconds', 'in seconds', 'MTN, Airtel, Glo & 9mobile — top up any number, any time', 'Buy airtime', ['Instant', 'All networks'], 'Top up any network in seconds — straight from your wallet.', `Credit finish? 📱\n\nTop up MTN, Airtel, Glo or 9mobile in seconds on ZAPPI PAY. Any number, any time, any amount ⚡\n\n${SITE}\n#ZappiPay #Airtime #Naija`),
  ad('data', 'Data', '📶', 'blue', '/buy/data', 'Data finish? No wahala', 'No wahala', 'Cheap data plans for every network — delivered instantly', 'Buy data', ['SME', 'Gifting', 'Corporate'], 'Cheap data for every network, delivered instantly.', `Data finish? No wahala 😄\n\nGet affordable data plans for MTN, Airtel, Glo and 9mobile on ZAPPI PAY — delivered instantly 📶\n\n${SITE}\n#ZappiPay #CheapData #BuyData`),
  ad('electricity', 'Electricity', '💡', 'gold', '/buy/electricity', 'Light token in seconds', 'in seconds', 'Prepaid & postpaid for every DisCo — your token comes straight to the app', 'Buy electricity', ['Prepaid', 'Postpaid', 'All DisCos'], 'Pay any DisCo — your token shows in the app instantly.', `NEPA don bring light, but units don finish? 💡😅\n\nBuy prepaid or postpaid electricity for any DisCo on ZAPPI PAY. Your meter is checked first and your token comes in seconds ⚡\n\n${SITE}\n#ZappiPay #Electricity #PrepaidMeter`),
  ad('cable', 'Cable TV', '📺', 'red', '/buy/cable', 'Renew your TV, no stress', 'no stress', 'DStv, GOtv, StarTimes & Showmax — we check your smartcard first', 'Renew now', ['DStv', 'GOtv', 'StarTimes'], 'Renew DStv, GOtv or StarTimes in seconds.', `Match about to start and your decoder don off? 📺⚽\n\nRenew DStv, GOtv, StarTimes or Showmax on ZAPPI PAY in seconds. We check your smartcard before you pay ✅\n\n${SITE}\n#ZappiPay #DStv #GOtv`),
  ad('internet', 'Internet', '🌐', 'blue', '/buy/internet', 'Stay connected', 'connected', 'Smile, Spectranet & more — renew your internet plan instantly', 'Renew internet', ['Smile', 'Spectranet'], 'Renew Smile or Spectranet in seconds.', `Work from home? Stay connected 🌐\n\nRenew your Smile or Spectranet plan on ZAPPI PAY in seconds — no queue, no stress.\n\n${SITE}\n#ZappiPay #Internet #Smile #Spectranet`),
  ad('betting', 'Bet funding', '⚽', 'green', '/buy/betting', 'Fund your bet wallet fast', 'fast', 'Bet9ja, SportyBet, BetKing & more — instant funding', 'Fund now', ['Instant', 'Account checked'], 'Fund your betting wallet instantly. 18+ only — play responsibly.', `Fund your betting wallet in seconds ⚽\n\nBet9ja, SportyBet, BetKing and more — instant funding on ZAPPI PAY. 18+ only. Please play responsibly.\n\n${SITE}\n#ZappiPay #BetFunding`),
  ad('send-money', 'Send money', '💸', 'purple', '/transfer', 'Send money free, instantly', 'free, instantly', 'To any ZAPPI PAY user by username, phone or QR', 'Send money', ['Free to users', 'QR pay'], 'Send money to friends free — by username, phone or QR.', `Send money to friends and family in seconds 💸\n\nFree between ZAPPI PAY users — just their username, phone number or QR code. You can also send to any bank 🏦\n\n${SITE}\n#ZappiPay #SendMoney`),
  ad('airtime-cash', 'Airtime to Cash', '🔁', 'green', '/airtime-cash', 'Turn airtime into cash', 'cash', 'Bought too much airtime? Convert it back to wallet money', 'Convert now', ['MTN', 'Airtel', 'Glo'], 'Turn extra airtime back into wallet money.', `Bought airtime by mistake or have too much? 🔁\n\nConvert it back to cash in your ZAPPI PAY wallet. Simple and fast 💰\n\n${SITE}\n#ZappiPay #AirtimeToCash`),
  ad('bulk', 'Bulk airtime & data', '👥', 'gold', '/bulk', 'Top up 50 numbers at once', '50 numbers', 'Staff, family, customers — one payment, everyone gets theirs', 'Try bulk', ['Staff', 'Family', 'Customers'], 'Send airtime or data to up to 50 numbers at once.', `Need to top up your staff, family or customers? 👥\n\nSend airtime or data to up to 50 numbers at once on ZAPPI PAY. One payment — everyone gets theirs ✅\n\n${SITE}\n#ZappiPay #BulkData #BulkAirtime`),
  ad('print-cards', 'Print recharge cards', '🖨️', 'dark', '/print-cards', 'Print recharge cards', 'recharge cards', 'Agents & shops: print MTN, Airtel, Glo & 9mobile cards and sell for profit', 'Start printing', ['Agents', 'Shops', 'POS printer'], 'Print and sell recharge cards from your shop.', `Run a shop or POS business? 🖨️\n\nPrint MTN, Airtel, Glo and 9mobile recharge cards on ZAPPI PAY and sell for profit. Works with A4 and POS printers.\n\n${SITE}\n#ZappiPay #RechargeCards #POSBusiness`),
  ad('gift', 'Gift airtime & data', '🎁', 'red', '/buy/airtime', 'Surprise someone today', 'Surprise', 'Send airtime or data as a gift with your own message', 'Send a gift', ['Birthdays', 'Just because'], 'Send airtime or data as a gift with a sweet message.', `Make someone smile today 🎁\n\nSend airtime or data as a gift on ZAPPI PAY — add your own message and they get a beautiful gift card 💝\n\n${SITE}\n#ZappiPay #GiftData #Love`),
  ad('refer', 'Refer & earn', '🤝', 'purple', '/refer', 'Invite friends, earn cash', 'earn cash', 'Share your code — you earn when they join and buy', 'Refer & earn', ['Your code', 'Real cash'], 'Invite friends with your code and earn.', `Earn money just by sharing 🤝\n\nInvite your friends to ZAPPI PAY with your referral code — you earn when they join and buy. The more you share, the more you earn 💰\n\n${SITE}\n#ZappiPay #ReferAndEarn`),
  ad('agent', 'Become an agent', '🏪', 'gold', '/profile', 'Become a ZAPPI PAY agent', 'agent', 'Cheaper prices, your own shop link and a profit book', 'Apply now', ['Agent prices', 'Shop link'], 'Agents get cheaper prices and their own shop link.', `Turn your phone into a business 🏪\n\nBecome a ZAPPI PAY agent: get cheaper prices, your own shop link and a profit book to track sales. Apply in the app today 📈\n\n${SITE}\n#ZappiPay #POSAgent #SmallBusiness`),
  ad('wallet', 'Fund your wallet', '🏦', 'blue', '/wallet', 'Your own account number', 'account number', 'Transfer from any bank and your wallet is funded automatically', 'Fund wallet', ['Automatic', '24/7'], 'Get your personal account number — funding is automatic.', `Fund your wallet the easy way 🏦\n\nGet your own ZAPPI PAY account number. Transfer from any bank app and your wallet is credited automatically, 24/7 ⚡\n\n${SITE}\n#ZappiPay #Fintech #Naija`),
];

export const READY_ADS = [
  {
    group: 'new',
    key: 'ajo-circle',
    name: 'Ajo Circle',
    headline: 'Ajo, the safe way',
    highlight: 'safe way',
    subtext: 'Save with people you trust. Paid automatically, in turn — the pot stays locked till everyone pays',
    cta: 'Start a circle',
    badges: ['Ajo', 'Esusu', 'Adashe'],
    emoji: '🔄',
    theme: 'purple',
    link: '/circles',
    inApp: 'Start an Ajo Circle — automatic contributions, paid in turn, locked pot.',
    caption: 'Ajo, esusu, adashe — now the safe way 🔄\n\nStart an Ajo Circle on ZAPPI PAY: everyone’s contribution is taken automatically, the pot stays locked where all members can see it, and each person gets paid in turn. No more chasing people 🙌\n\n👉 www.zappipay.com.ng\n#ZappiPay #Ajo #Esusu #Adashe #SaveTogether',
  },
  {
    group: 'new',
    key: 'pay-me-link',
    name: 'Pay me link',
    headline: 'Get paid with one link',
    highlight: 'one link',
    subtext: 'Create a Pay-me link, share it on WhatsApp — friends pay straight into your wallet',
    cta: 'Create my link',
    badges: ['Free', 'Instant', 'Any bank app'],
    emoji: '🔗',
    theme: 'purple',
    link: '/requests',
    inApp: 'Ask for money with a link — they pay, your wallet gets it instantly.',
    caption: 'Stop sending account numbers up and down 😅\n\nWith ZAPPI PAY, create a Pay-me link, share it on WhatsApp, and get paid straight into your wallet. Free and instant ⚡\n\n👉 www.zappipay.com.ng\n#ZappiPay #PayMeLink #GetPaid #Naija',
  },
  {
    group: 'new',
    key: 'split-bill',
    name: 'Split a bill',
    headline: 'Split the bill, no wahala',
    highlight: 'no wahala',
    subtext: 'Dinner, rent, fuel — ZAPPI PAY splits it and tracks who has paid',
    cta: 'Split a bill',
    badges: ['Track who paid', 'Reminders'],
    emoji: '🧾',
    theme: 'blue',
    link: '/requests',
    inApp: 'Split dinner, rent or fuel — see who has paid and who hasn’t.',
    caption: '"I go send am later" — we know that one 😂\n\nSplit any bill on ZAPPI PAY: everyone gets a link, pays their share, and you see who has paid. No more chasing people 🙌\n\n👉 www.zappipay.com.ng\n#ZappiPay #SplitTheBill #Naija',
  },
  {
    group: 'new',
    key: 'group-gift',
    name: 'Group gift',
    headline: 'Chip in for a group gift',
    highlight: 'group gift',
    subtext: 'Birthday, wedding, send-forth — collect contributions in one place',
    cta: 'Start a collection',
    badges: ['Birthdays', 'Weddings', 'Send-forth'],
    emoji: '🎁',
    theme: 'gold',
    link: '/requests',
    inApp: 'Birthday or wedding coming? Collect everyone’s contribution with one link.',
    caption: 'Birthday, wedding or send-forth loading? 🎉\n\nStart a group gift on ZAPPI PAY, share one link, and watch the contributions come in. Everyone can see the total 💛\n\n👉 www.zappipay.com.ng\n#ZappiPay #GroupGift #Owambe',
  },
  {
    group: 'new',
    key: 'car-insurance',
    name: 'Car insurance',
    headline: 'Car papers? Insurance in minutes',
    highlight: 'in minutes',
    subtext: 'Third-party motor insurance by Universal Insurance — certificate sent to your email',
    cta: 'Insure my car',
    badges: ['Cars', 'Buses', 'Keke & bikes'],
    emoji: '🚗',
    theme: 'green',
    link: '/insurance',
    inApp: 'Third-party motor insurance in minutes — certificate straight to your email.',
    caption: 'No more running around for car papers 🚗💨\n\nBuy third-party motor insurance on ZAPPI PAY in minutes — for cars, buses, keke and bikes. Your certificate comes straight to your email ✅\n\n👉 www.zappipay.com.ng\n#ZappiPay #CarInsurance #ThirdPartyInsurance',
  },
  {
    group: 'new',
    key: 'exam-pins',
    name: 'Bulk WAEC PINs',
    headline: 'WAEC PINs in bulk',
    highlight: 'in bulk',
    subtext: 'Buy up to 50 result checker PINs at once — print them on A4 or POS paper',
    cta: 'Buy exam PINs',
    badges: ['Schools', 'Cyber cafés', 'Agents'],
    emoji: '🎓',
    theme: 'dark',
    link: '/exam-pins',
    inApp: 'Schools & cyber cafés: buy up to 50 WAEC PINs at once and print them.',
    caption: 'Schools, cyber cafés and agents 📢\n\nBuy up to 50 WAEC result checker PINs at once on ZAPPI PAY, then print them neatly on A4 or your POS printer 🖨️ Agent prices apply.\n\n👉 www.zappipay.com.ng\n#ZappiPay #WAEC #ResultChecker #Schools',
  },
  {
    group: 'new',
    key: 'jamb-pin',
    name: 'JAMB PIN',
    headline: 'JAMB PIN without stress',
    highlight: 'without stress',
    subtext: 'Enter your Profile ID, we check your name, you get your PIN instantly',
    cta: 'Buy JAMB PIN',
    badges: ['UTME', 'With or without mock'],
    emoji: '📚',
    theme: 'red',
    link: '/buy/education',
    inApp: 'Buy your JAMB UTME PIN in seconds — your Profile ID is checked first.',
    caption: 'JAMB registration loading? 📚\n\nBuy your UTME PIN on ZAPPI PAY: enter your Profile ID, we confirm your name, and your PIN comes instantly. No queue, no stress ✅\n\n👉 www.zappipay.com.ng\n#ZappiPay #JAMB #UTME',
  },
];


// The switchable features (Admin → New features). Only post these once
// the feature is ON for customers.
export const FEATURE_ADS = [
  ad('owambe-spray', 'Owambe Spray', '💃', 'red', '/spray', 'Spray money from your phone', 'from your phone', 'No cash, no wahala. Guests scan, tap SPRAY — it lands in the celebrant’s wallet instantly', 'Start a spray event', ['Weddings', 'Birthdays', 'Naming'], 'Owambe this weekend? Let guests spray from their phones 💃', `Owambe this weekend? 💃💸\n\nWith Owambe Spray on ZAPPI PAY, guests scan your QR code and tap SPRAY — the money lands in the celebrant’s wallet instantly, with notes flying on the big screen and a leaderboard of top sprayers 🏆\n\nNo cash to count, nobody picking money from the floor.\n\n${SITE}\n#ZappiPay #Owambe #SprayMoney #NaijaWedding`, 'features'),
  ad('association-dues', 'Association Dues', '🏘️', 'blue', '/dues', 'Collect dues without chasing', 'without chasing', 'Estate, church, mosque, alumni & club dues — reminders, auto-pay and a paid/unpaid list', 'Start collecting', ['Estates', 'Churches', 'Alumni'], 'Treasurer? Collect dues with reminders and auto-pay 🏘️', `Treasurers, this one is for you 🏘️\n\nCollect estate, church, mosque, alumni or club dues on ZAPPI PAY: members pay with one tap or switch on auto-pay, reminders go out automatically, and you see exactly who has paid ✅\n\nNo more “I’ll pay next week”.\n\n${SITE}\n#ZappiPay #Dues #EstateLife #Treasurer`, 'features'),
  ad('pay-for-me', 'Pay It For Me', '🙏', 'purple', '/pay-for-me', 'Ask them to pay it for you', 'pay it for you', 'Send a link — they pay your light, data or DStv and it comes straight to you', 'Ask someone to pay', ['Light', 'Data', 'TV'], 'Need help with light or data? Send a Pay It For Me link 🙏', `“Abeg help me pay my light” — now with one link 🙏💡\n\nFill in your meter, number or decoder on ZAPPI PAY, tap “Ask someone to pay” and send the link. Whoever pays, it goes straight to YOU — no cash, no excuses 😄\n\n${SITE}\n#ZappiPay #PayItForMe #Family #Nigeria`, 'features'),
  ad('shared-light', 'Shared Light', '💡', 'gold', '/shared-light', 'Split the light bill, fairly', 'fairly', 'Housemates fill one pot — the token buys itself when it’s full', 'Start a light pot', ['Flatmates', 'Compounds', 'Shops'], 'Sharing a meter? Fill one pot and the token buys itself 💡', `Sharing one meter with housemates? 💡\n\nStart a Shared Light pot on ZAPPI PAY. Everyone puts in their share, and the moment the pot is full the token is bought automatically. Everyone can see who has paid 👀\n\nNo more “who never pay?” palaver.\n\n${SITE}\n#ZappiPay #SharedLight #NEPA #Flatmates`, 'features'),
  ad('safebuy', 'SafeBuy', '🛡️', 'green', '/safebuy', 'Buy online without fear', 'without fear', 'Your money is held until you confirm you got the item', 'Use SafeBuy', ['WhatsApp', 'Instagram', 'Vendors'], 'Buying from a vendor online? Pay with SafeBuy 🛡️', `Buying from an Instagram or WhatsApp vendor? 🛡️\n\nAsk them for a ZAPPI PAY SafeBuy link. Your money is HELD until you confirm you received the item — then the seller is paid. Problem? Report it and the money stays held while we check.\n\nVendors: SafeBuy links help buyers trust you 💪\n\n${SITE}\n#ZappiPay #SafeBuy #BuyerProtection #ShopSafe`, 'features'),
  ad('payroll', 'Payroll', '💼', 'dark', '/payroll', 'Pay all your staff in one tap', 'one tap', 'Shop staff, workers, helpers — wallet (free, instant) or any bank', 'Set up payroll', ['Shops', 'Salons', 'Small business'], 'Small business? Pay all your staff in one tap 💼', `Small business owners 💼\n\nAdd your staff once on ZAPPI PAY, set their salaries, and pay everyone in one tap — to their ZAPPI PAY wallet (free and instant) or any bank. Everyone gets a payslip message ✅\n\n${SITE}\n#ZappiPay #Payroll #SmallBusiness #SME`, 'features'),
  ad('daily-rewards', 'Daily rewards', '🎁', 'purple', '/rewards', 'Check in daily, earn cashback', 'earn cashback', 'Keep your streak and answer the question of the day', 'Check in now', ['Streaks', 'Quiz', 'Cashback'], 'Check in today and answer the question of the day 🎁', `Free cashback, every day 🎁\n\nOpen ZAPPI PAY, check in, and answer the question of the day. Keep your streak for 7 days for a bonus 🔥 Rewards go straight to your cashback balance.\n\n${SITE}\n#ZappiPay #DailyRewards #Cashback`, 'features'),
];

export const ALL_READY_ADS = [...READY_ADS, ...FEATURE_ADS, ...CORE_ADS];
